name: Telegram Bot Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg aria2

      - name: Install All Python Modules
        run: |
          pip install --upgrade pip
          pip install pyromod m3u8 pytube requests yt-dlp pyrogram tgcrypto aiohttp aiofiles motor python-dotenv beautifulsoup4 mutagen ffmpeg-python cryptography pycryptodome cloudscraper PyYaml Pillow urllib3 pscript pdfplumber PyPDF2 reportlab

      - name: Run 3 Bots Parallelly
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_TOKEN_2: ${{ secrets.BOT_TOKEN_2 }}
          BOT_TOKEN_3: ${{ secrets.BOT_TOKEN_3 }}
        run: |
          # Pehle bot ke liye setup aur run
          mkdir -p bot1 && cp -r modules bot1/
          cd bot1
          PYTHONPATH=modules BOT_TOKEN="$BOT_TOKEN" python modules/main.py &
          cd ..

          # Dusre bot ke liye setup aur run (agar BOT_TOKEN_2 set hai)
          if [ -n "$BOT_TOKEN_2" ]; then
            mkdir -p bot2 && cp -r modules bot2/
            cd bot2
            PYTHONPATH=modules BOT_TOKEN="$BOT_TOKEN_2" python modules/main.py &
            cd ..
          fi

          # Teesre bot ke liye setup aur run (agar BOT_TOKEN_3 set hai)
          if [ -n "$BOT_TOKEN_3" ]; then
            mkdir -p bot3 && cp -r modules bot3/
            cd bot3
            PYTHONPATH=modules BOT_TOKEN="$BOT_TOKEN_3" python modules/main.py &
            cd ..
          fi

          # Sabhi processes ko live rakhne ke liye
          wait
